// ── BOOK TYPE DEFINITIONS ──
// Interfaces for books throughout the application

/**
 * Represents a book in the MiniLib catalog
 * Corresponds to the livres table in PostgreSQL
 * Immutable once created (except disponible flag)
 * 
 * @prop id - Unique identifier (SERIAL PRIMARY KEY)
 * @prop isbn - International Standard Book Number
 * @prop titre - Book title
 * @prop auteur - Book author
 * @prop annee - Publication year
 * @prop genre - Book genre/category
 * @prop disponible - Whether the book is currently available to borrow
 */
export interface Livre {
    id: number;
    isbn: string;
    titre: string;
    auteur: string;
    annee: number;
    genre: string;
    disponible: boolean;
}

/**
 * Data structure for creating a new book
 * Used in POST requests and model.create()
 * Excludes id (auto-generated by PostgreSQL SERIAL)
 * Excludes disponible (defaults to true)
 * 
 * @prop isbn - Required: International Standard Book Number
 * @prop titre - Required: Book title
 * @prop auteur - Required: Book author
 * @prop annee - Optional: Publication year
 * @prop genre - Optional: Book genre/category
 */
export interface CreateLivreDto {
    isbn: string;
    titre: string;
    auteur: string;
    annee?: number;
    genre?: string;
}

/**
 * Optional filters for fetching/searching books
 * Used in GET queries with query parameters
 * All properties are optional
 * 
 * @prop genre - Filter by specific genre
 * @prop disponible - Filter by availability (true/false)
 * @prop recherche - Search in titre or auteur fields (case-insensitive)
 */
export interface FiltresLivre {
    genre?: string;
    disponible?: boolean;
    recherche?: string;
}